// Crew-language display for PLATFORM-SEEDED data strings.
//
// The checklist rows, room names, supply/linen catalog and units the crew
// sees are rows the owner's account holds — Rinsebase seeds them in English
// (DB triggers `seed_default_checklist_for_address`, `turnover_room_template`,
// `room_display_name`, `seed_default_supplies_for_address`, plus the web
// app's checklist templates and linen one-tap list). Owners rarely rename
// them, so a Spanish- or Portuguese-speaking cleaner used to see a translated
// frame around English content.
//
// `tv(lang, text)` maps a seeded English string to the crew's language for
// DISPLAY ONLY. Anything the owner typed themselves passes through unchanged,
// and nothing translated here is ever written back — incident titles, restock
// notes and linen flags keep the English catalog name so the office reads one
// vocabulary whatever language the crew works in.
//
// Matching is case- and whitespace-insensitive, and a trailing instance number
// ("Bedroom 2", "Living Room 2") is carried over from the base entry.

import type { Language } from './i18n'

// [es, pt]
const V: Record<string, [string, string]> = {
  // ── Rooms — room_display_name(), legacy address templates, mobile defaults
  'Arrival': ['Llegada', 'Chegada'],
  'Kitchen': ['Cocina', 'Cozinha'],
  'Living Room': ['Sala', 'Sala de estar'],
  'Dining Area': ['Comedor', 'Sala de jantar'],
  'Dining Room': ['Comedor', 'Sala de jantar'],
  'Primary Bedroom': ['Dormitorio principal', 'Quarto principal'],
  'Master Bedroom': ['Dormitorio principal', 'Quarto principal'],
  'Master': ['Dormitorio principal', 'Quarto principal'],
  'Bedroom': ['Dormitorio', 'Quarto'],
  'Bedrooms': ['Dormitorios', 'Quartos'],
  'Guest Bedroom': ['Dormitorio de huéspedes', 'Quarto de hóspedes'],
  'Bunk Room': ['Cuarto de literas', 'Quarto de beliches'],
  'Loft Bedroom': ['Dormitorio en el altillo', 'Quarto no mezanino'],
  'Loft Room': ['Altillo', 'Mezanino'],
  'Bathroom': ['Baño', 'Banheiro'],
  'Bathrooms': ['Baños', 'Banheiros'],
  'Primary Bathroom': ['Baño principal', 'Banheiro principal'],
  'Master Bathroom': ['Baño principal', 'Banheiro principal'],
  'Guest Bathroom': ['Baño de huéspedes', 'Banheiro de hóspedes'],
  'Half Bath': ['Medio baño', 'Lavabo'],
  'Powder Room': ['Medio baño', 'Lavabo'],
  'Laundry': ['Lavandería', 'Lavanderia'],
  'Laundry Room': ['Cuarto de lavado', 'Área de serviço'],
  'Laundry Area': ['Área de lavado', 'Área de serviço'],
  'Office': ['Oficina', 'Escritório'],
  'Game Room': ['Sala de juegos', 'Sala de jogos'],
  'Loft': ['Altillo', 'Mezanino'],
  'Patio / Deck': ['Patio / terraza', 'Pátio / deck'],
  'Patio': ['Patio', 'Pátio'],
  'Deck': ['Terraza', 'Deck'],
  'Front Patio': ['Patio delantero', 'Pátio da frente'],
  'Pool': ['Alberca', 'Piscina'],
  'Hot Tub': ['Jacuzzi', 'Banheira de hidromassagem'],
  'Grill': ['Asador', 'Churrasqueira'],
  'Garage': ['Cochera', 'Garagem'],
  'Garage / Game Room': ['Cochera / sala de juegos', 'Garagem / sala de jogos'],
  'Entry': ['Entrada', 'Entrada'],
  'Entry Way': ['Entrada', 'Entrada'],
  'Entryway': ['Entrada', 'Entrada'],
  'Exterior': ['Exterior', 'Área externa'],
  'Outdoor': ['Exterior', 'Área externa'],
  'Final Guest-Ready Check': ['Revisión final para el huésped', 'Verificação final para o hóspede'],
  'Final': ['Revisión final', 'Verificação final'],
  'Other': ['Otro', 'Outro'],
  'All rooms': ['Todas las habitaciones', 'Todos os cômodos'],
  'All Rooms': ['Todas las habitaciones', 'Todos os cômodos'],
  'General': ['General', 'Geral'],
  'Floors': ['Pisos', 'Pisos'],
  'Room': ['Habitación', 'Cômodo'],
  'Security': ['Seguridad', 'Segurança'],
  'Whole property': ['Toda la propiedad', 'Propriedade inteira'],
  // commercial / medical rooms (web templates)
  'Reception': ['Recepción', 'Recepção'],
  'Open Workspace': ['Área de trabajo abierta', 'Área de trabalho aberta'],
  'Private Office': ['Oficina privada', 'Escritório privativo'],
  'Conference Room': ['Sala de juntas', 'Sala de reuniões'],
  'Restroom': ['Sanitario', 'Banheiro'],
  'Restrooms': ['Sanitarios', 'Banheiros'],
  'Break Room': ['Comedor de empleados', 'Copa'],
  'Breakroom': ['Comedor de empleados', 'Copa'],
  'Corridor': ['Pasillo', 'Corredor'],
  'Janitor Closet': ['Cuarto de limpieza', 'Depósito de limpeza'],
  'Waiting Room': ['Sala de espera', 'Sala de espera'],
  'Exam Room': ['Consultorio', 'Sala de exame'],
  'Treatment Room': ['Sala de tratamiento', 'Sala de tratamento'],
  'Lab / Sterilization': ['Laboratorio / esterilización', 'Laboratório / esterilização'],

  // ── Supplies — seed_default_supplies_for_address (STR + commercial), starter kit
  'Toilet paper': ['Papel higiénico', 'Papel higiênico'],
  'Paper towels': ['Toallas de papel', 'Papel-toalha'],
  'Trash bags': ['Bolsas de basura', 'Sacos de lixo'],
  'Trash bags (tall kitchen)': ['Bolsas de basura (cocina, altas)', 'Sacos de lixo (cozinha, grandes)'],
  'Trash liners': ['Bolsas para botes de basura', 'Sacos para lixeira'],
  'Can liners (55 gal)': ['Bolsas para contenedor (55 gal)', 'Sacos para contêiner (55 gal)'],
  'Dish soap': ['Jabón para trastes', 'Detergente de louça'],
  'Dishwasher pods': ['Cápsulas para lavavajillas', 'Pastilhas para lava-louças'],
  'Hand soap': ['Jabón de manos', 'Sabonete líquido'],
  'Hand soap refill': ['Repuesto de jabón de manos', 'Refil de sabonete líquido'],
  'Shampoo': ['Shampoo', 'Xampu'],
  'Conditioner': ['Acondicionador', 'Condicionador'],
  'Body wash': ['Gel de baño', 'Sabonete líquido corporal'],
  'Laundry detergent': ['Detergente para ropa', 'Sabão para roupas'],
  'Laundry pods': ['Cápsulas de detergente para ropa', 'Cápsulas de sabão para roupas'],
  'Liquid detergent': ['Detergente líquido', 'Sabão líquido'],
  'Detergent sheets': ['Hojas de detergente', 'Folhas de detergente'],
  'Dryer sheets': ['Toallitas para secadora', 'Lenços para secadora'],
  'Toilet seat covers': ['Cubreasientos para inodoro', 'Protetores de assento sanitário'],
  'Sanitary disposal bags': ['Bolsas para desechos sanitarios', 'Sacos para descarte sanitário'],
  'Neutral all-purpose cleaner': ['Limpiador multiusos neutro', 'Limpador multiuso neutro'],
  'Bathroom cleaner / disinfectant': ['Limpiador / desinfectante de baño', 'Limpador / desinfetante de banheiro'],
  'Glass & mirror cleaner': ['Limpiavidrios', 'Limpa-vidros'],
  'Stainless / appliance cleaner': ['Limpiador de acero inoxidable', 'Limpador de inox / eletrodomésticos'],
  'Microfiber cloths': ['Paños de microfibra', 'Panos de microfibra'],
  'Microfiber cloth set': ['Juego de paños de microfibra', 'Conjunto de panos de microfibra'],
  'Gloves': ['Guantes', 'Luvas'],
  'Coffee': ['Café', 'Café'],
  'Soap bar': ['Jabón en barra', 'Sabonete em barra'],
  'Vacuum': ['Aspiradora', 'Aspirador'],
  'Mop / floor system': ['Trapeador / sistema de pisos', 'Esfregão / sistema de piso'],
  'Caddy / carry bag': ['Caddy / bolsa de transporte', 'Caddy / bolsa de transporte'],
  'Linen transport bin': ['Contenedor para ropa de cama', 'Caixa de transporte de roupa de cama'],
  'Amenities': ['Amenidades', 'Amenidades'],

  // ── Linens — PropertyLinenEditor one-tap list, demo seed, common variants
  'King sheet set': ['Juego de sábanas king', 'Jogo de lençóis king'],
  'Queen sheet set': ['Juego de sábanas queen', 'Jogo de lençóis queen'],
  'Full sheet set': ['Juego de sábanas matrimonial', 'Jogo de lençóis casal'],
  'Twin sheet set': ['Juego de sábanas individual', 'Jogo de lençóis solteiro'],
  'Crib sheet set': ['Juego de sábanas para cuna', 'Jogo de lençóis de berço'],
  'King fitted sheet': ['Sábana ajustable king', 'Lençol com elástico king'],
  'King flat sheet': ['Sábana plana king', 'Lençol de cima king'],
  'Sheets for pull-out': ['Sábanas para sofá cama', 'Lençóis para sofá-cama'],
  'Pillowcases': ['Fundas de almohada', 'Fronhas'],
  'Bath towels': ['Toallas de baño', 'Toalhas de banho'],
  'Bath towel': ['Toalla de baño', 'Toalha de banho'],
  'Hand towels': ['Toallas de mano', 'Toalhas de rosto'],
  'Hand towel': ['Toalla de mano', 'Toalha de rosto'],
  'Washcloths': ['Toallitas faciales', 'Toalhinhas'],
  'Wash cloth': ['Toallita facial', 'Toalhinha'],
  'Bath mats': ['Tapetes de baño', 'Tapetes de banheiro'],
  'Bath mat': ['Tapete de baño', 'Tapete de banheiro'],
  'Kitchen towels': ['Toallas de cocina', 'Panos de prato'],
  'Beach towels': ['Toallas de playa', 'Toalhas de praia'],
  'Beach towel': ['Toalla de playa', 'Toalha de praia'],
  'Spa towels': ['Toallas de spa', 'Toalhas de spa'],
  'Makeup cloths': ['Toallitas desmaquillantes', 'Toalhinhas de maquiagem'],
  'Makeup cloth': ['Toallita desmaquillante', 'Toalhinha de maquiagem'],
  'Makeup washcloths': ['Toallitas desmaquillantes', 'Toalhinhas de maquiagem'],
  'Linens': ['Ropa de cama', 'Roupa de cama'],

  // ── Supply categories (address_inventory.category)
  'Paper': ['Papel', 'Papel'],
  'Chemicals': ['Químicos', 'Químicos'],
  'Supplies': ['Insumos', 'Suprimentos'],

  // ── Units (address_inventory.unit)
  'rolls': ['rollos', 'rolos'],
  'roll': ['rollo', 'rolo'],
  'bags': ['bolsas', 'sacos'],
  'bag': ['bolsa', 'saco'],
  'pods': ['cápsulas', 'cápsulas'],
  'bottle': ['botella', 'frasco'],
  'bottles': ['botellas', 'frascos'],
  'sets': ['juegos', 'jogos'],
  'set': ['juego', 'jogo'],
  'packs': ['paquetes', 'pacotes'],
  'pack': ['paquete', 'pacote'],
  'packages': ['paquetes', 'pacotes'],
  'package': ['paquete', 'pacote'],
  'liners': ['bolsas', 'sacos'],
  'boxes': ['cajas', 'caixas'],
  'box': ['caja', 'caixa'],
  'each': ['c/u', 'un.'],
  'bars': ['barras', 'barras'],
  'jug': ['garrafa', 'galão'],
  'jugs': ['garrafas', 'galões'],
  'gallon': ['galón', 'galão'],

  // ── Legacy address checklist seed (seed_default_checklist_for_address /
  //    "Standard STR Turnover" web template) — 27 of 29 active tenants
  'Wipe all countertops and backsplash': ['Limpiar todas las cubiertas y el salpicadero', 'Limpar todas as bancadas e o revestimento'],
  'Clean stovetop, oven exterior, and microwave (inside + out)': ['Limpiar estufa, exterior del horno y microondas (por dentro y por fuera)', 'Limpar fogão, exterior do forno e micro-ondas (dentro e fora)'],
  'Wipe fridge exterior and interior shelves; toss expired food': ['Limpiar el refrigerador por fuera y los estantes; tirar comida caducada', 'Limpar a geladeira por fora e as prateleiras; descartar comida vencida'],
  'Wash and put away all dishes, run dishwasher if needed': ['Lavar y guardar todos los trastes; correr el lavavajillas si hace falta', 'Lavar e guardar toda a louça; rodar a lava-louças se necessário'],
  'Empty trash and recycling, replace liners': ['Vaciar basura y reciclaje, poner bolsas nuevas', 'Esvaziar lixo e reciclagem, trocar os sacos'],
  'Sweep and mop floor': ['Barrer y trapear el piso', 'Varrer e passar pano no piso'],
  'Restock coffee, tea, salt, pepper, dish soap': ['Reponer café, té, sal, pimienta, jabón para trastes', 'Repor café, chá, sal, pimenta, detergente de louça'],
  'Vacuum couch and chair cushions, check between cushions': ['Aspirar cojines del sofá y sillones, revisar entre los cojines', 'Aspirar almofadas do sofá e poltronas, verificar entre as almofadas'],
  'Dust all surfaces, tables, shelves, electronics': ['Sacudir todas las superficies, mesas, repisas, electrónicos', 'Tirar o pó de todas as superfícies, mesas, prateleiras, eletrônicos'],
  'Wipe TV screen and remote with microfiber': ['Limpiar pantalla de TV y control con microfibra', 'Limpar a tela da TV e o controle com microfibra'],
  'Fluff pillows, fold and arrange throws': ['Esponjar cojines, doblar y acomodar mantas', 'Ajeitar almofadas, dobrar e arrumar mantas'],
  'Vacuum and/or mop floor': ['Aspirar y/o trapear el piso', 'Aspirar e/ou passar pano no piso'],
  'Strip and remake bed with fresh linens': ['Quitar y tender la cama con ropa limpia', 'Desfazer e arrumar a cama com roupa limpa'],
  'Dust nightstands, lamps, dresser, headboard': ['Sacudir burós, lámparas, cómoda, cabecera', 'Tirar o pó de criados-mudos, abajures, cômoda, cabeceira'],
  'Empty closet, check for left-behind items': ['Vaciar el clóset, revisar si quedaron objetos', 'Esvaziar o armário, verificar itens esquecidos'],
  'Vacuum floor and under bed': ['Aspirar el piso y debajo de la cama', 'Aspirar o piso e embaixo da cama'],
  'Scrub toilet inside, outside, and base': ['Tallar el inodoro por dentro, por fuera y la base', 'Esfregar o vaso por dentro, por fora e na base'],
  'Clean shower walls, glass, and drain': ['Limpiar paredes de la regadera, vidrio y coladera', 'Limpar paredes do chuveiro, vidro e ralo'],
  'Polish sink, faucet, and mirror': ['Pulir lavabo, llave y espejo', 'Polir pia, torneira e espelho'],
  'Restock toilet paper, soap, shampoo, conditioner': ['Reponer papel higiénico, jabón, shampoo, acondicionador', 'Repor papel higiênico, sabonete, xampu, condicionador'],
  'Replace bath mat, hand towels, and washcloths': ['Cambiar tapete de baño, toallas de mano y toallitas', 'Trocar tapete de banheiro, toalhas de rosto e toalhinhas'],
  'Mop floor': ['Trapear el piso', 'Passar pano no piso'],
  'Dust all surfaces and vacuum floor': ['Sacudir todas las superficies y aspirar el piso', 'Tirar o pó de todas as superfícies e aspirar o piso'],
  'Scrub toilet, shower, sink, and mirror': ['Tallar inodoro, regadera, lavabo y espejo', 'Esfregar vaso, chuveiro, pia e espelho'],
  'Restock paper, soap, and towels': ['Reponer papel, jabón y toallas', 'Repor papel, sabonete e toalhas'],
  'Sweep patio/deck and arrange furniture': ['Barrer patio/terraza y acomodar muebles', 'Varrer pátio/deck e arrumar os móveis'],
  'Check grill is clean and propane connected': ['Revisar que el asador esté limpio y el gas conectado', 'Verificar se a churrasqueira está limpa e o gás conectado'],
  'Wash all used linens and towels': ['Lavar toda la ropa de cama y toallas usadas', 'Lavar toda a roupa de cama e toalhas usadas'],
  'Empty lint trap, wipe washer/dryer exterior': ['Vaciar el filtro de pelusa, limpiar lavadora/secadora por fuera', 'Esvaziar o filtro de fiapos, limpar lavadora/secadora por fora'],
  'Check thermostat — set to 72°F before leaving': ['Revisar el termostato — dejarlo en 72 °F antes de salir', 'Verificar o termostato — deixar em 72 °F antes de sair'],
  'Lock all doors and windows': ['Cerrar con llave todas las puertas y ventanas', 'Trancar todas as portas e janelas'],
  'Turn off all lights except entry': ['Apagar todas las luces menos la de la entrada', 'Apagar todas as luzes, exceto a da entrada'],

  // ── turnover_room_template() — room-spine checklist
  'Verify property is vacant / authorized to enter': ['Verificar que la propiedad esté vacía / autorización para entrar', 'Verificar se a propriedade está vazia / autorização para entrar'],
  'Note any unusual condition or excessive mess': ['Anotar cualquier condición inusual o desorden excesivo', 'Anotar qualquer condição incomum ou bagunça excessiva'],
  'Lock / keypad works': ['La cerradura / teclado funciona', 'Fechadura / teclado funciona'],
  'No signs of pests, odor, or water damage': ['Sin señales de plagas, olores o daños por agua', 'Sem sinais de pragas, odor ou danos por água'],
  'Arrival-condition photo (only if something is off)': ['Foto de la condición al llegar (solo si algo está mal)', 'Foto da condição na chegada (só se algo estiver errado)'],
  'Remove trash and leftover food': ['Sacar la basura y la comida sobrante', 'Retirar lixo e restos de comida'],
  'Clean and sanitize counters and surfaces': ['Limpiar y desinfectar cubiertas y superficies', 'Limpar e higienizar bancadas e superfícies'],
  'Clean sink and faucet': ['Limpiar tarja y llave', 'Limpar pia e torneira'],
  'Clean appliance exteriors': ['Limpiar electrodomésticos por fuera', 'Limpar o exterior dos eletrodomésticos'],
  'Clean stovetop and microwave': ['Limpiar estufa y microondas', 'Limpar fogão e micro-ondas'],
  'Sweep, vacuum, or mop floor': ['Barrer, aspirar o trapear el piso', 'Varrer, aspirar ou passar pano no piso'],
  'Reset and stage to property standard': ['Acomodar según el estándar de la propiedad', 'Arrumar conforme o padrão da propriedade'],
  'Fridge and freezer cold and empty of guest food': ['Refrigerador y congelador fríos y sin comida del huésped', 'Geladeira e freezer gelados e sem comida do hóspede'],
  'Dishwasher empty; dishes put away': ['Lavavajillas vacío; trastes guardados', 'Lava-louças vazia; louça guardada'],
  'Stove / oven ignites': ['La estufa / horno enciende', 'Fogão / forno acende'],
  'Coffee setup and kitchen supplies at par': ['Estación de café e insumos de cocina completos', 'Estação de café e suprimentos de cozinha no nível'],
  'Disposal runs; sink drains': ['El triturador funciona; la tarja drena', 'Triturador funciona; a pia escoa'],
  'Guest-ready kitchen': ['Cocina lista para el huésped', 'Cozinha pronta para o hóspede'],
  'Remove trash and guest belongings': ['Sacar basura y pertenencias del huésped', 'Retirar lixo e pertences do hóspede'],
  'Dust and wipe surfaces': ['Sacudir y limpiar superficies', 'Tirar o pó e limpar superfícies'],
  'Reset furniture and cushions': ['Acomodar muebles y cojines', 'Arrumar móveis e almofadas'],
  'Clean floors': ['Limpiar pisos', 'Limpar o piso'],
  'Clean floor': ['Limpiar el piso', 'Limpar o piso'],
  'TV and remotes power on': ['La TV y los controles encienden', 'TV e controles ligam'],
  'Wi-Fi card / guest info present': ['Tarjeta de Wi-Fi / info del huésped presente', 'Cartão de Wi-Fi / informações do hóspede presentes'],
  'Seating free of crumbs and hair': ['Asientos sin migajas ni cabello', 'Assentos sem migalhas nem cabelos'],
  'Lights and lamps work': ['Luces y lámparas funcionan', 'Luzes e abajures funcionam'],
  'Guest-ready living area': ['Sala lista para el huésped', 'Sala pronta para o hóspede'],
  'Wipe table and chairs': ['Limpiar mesa y sillas', 'Limpar mesa e cadeiras'],
  'Clean floor under and around table': ['Limpiar el piso debajo y alrededor de la mesa', 'Limpar o piso embaixo e ao redor da mesa'],
  'Reset and stage': ['Acomodar y preparar', 'Arrumar e preparar'],
  'Chairs and table stable; nothing sticky': ['Sillas y mesa firmes; nada pegajoso', 'Cadeiras e mesa firmes; nada grudento'],
  'Guest-ready dining area': ['Comedor listo para el huésped', 'Sala de jantar pronta para o hóspede'],
  'Strip and check used linens': ['Quitar y revisar la ropa de cama usada', 'Retirar e verificar a roupa de cama usada'],
  'Inspect mattress and protector': ['Revisar colchón y protector', 'Inspecionar colchão e protetor'],
  'Make bed to property standard': ['Tender la cama según el estándar de la propiedad', 'Arrumar a cama conforme o padrão da propriedade'],
  'Clean mirrors': ['Limpiar espejos', 'Limpar espelhos'],
  'Clean mirror': ['Limpiar el espejo', 'Limpar o espelho'],
  'Vacuum or mop floor': ['Aspirar o trapear el piso', 'Aspirar ou passar pano no piso'],
  'Reset and stage room': ['Acomodar y preparar la habitación', 'Arrumar e preparar o quarto'],
  'No guest belongings in drawers, closet, or under bed': ['Sin pertenencias del huésped en cajones, clóset o bajo la cama', 'Sem pertences do hóspede em gavetas, armário ou embaixo da cama'],
  'Lamps and outlets work': ['Lámparas y enchufes funcionan', 'Abajures e tomadas funcionam'],
  'HVAC vent clear and blowing': ['Rejilla de aire despejada y con flujo', 'Saída de ar desobstruída e soprando'],
  'Required linen set present (pillows, sheets, blanket)': ['Juego de ropa de cama completo (almohadas, sábanas, cobija)', 'Jogo de roupa de cama completo (travesseiros, lençóis, cobertor)'],
  'Blinds / curtains operate': ['Persianas / cortinas funcionan', 'Persianas / cortinas funcionam'],
  'Finished bed / guest-ready room': ['Cama tendida / habitación lista para el huésped', 'Cama arrumada / quarto pronto para o hóspede'],
  'Clean and disinfect toilet': ['Limpiar y desinfectar el inodoro', 'Limpar e desinfetar o vaso'],
  'Clean shower and tub': ['Limpiar regadera y tina', 'Limpar chuveiro e banheira'],
  'Clean sink and vanity': ['Limpiar lavabo y tocador', 'Limpar pia e bancada'],
  'Replace and stage towels': ['Cambiar y acomodar toallas', 'Trocar e arrumar toalhas'],
  'Restock toiletries and paper products': ['Reponer artículos de aseo y papel', 'Repor itens de higiene e papel'],
  'Toilet flushes and refills': ['El inodoro descarga y se llena', 'O vaso dá descarga e enche'],
  'Hot water available': ['Hay agua caliente', 'Água quente disponível'],
  'Drains flow normally': ['Los desagües drenan bien', 'Ralos escoam normalmente'],
  'Exhaust fan works': ['El extractor funciona', 'Exaustor funciona'],
  'Amenities at par; no hair on any surface': ['Amenidades completas; sin cabello en ninguna superficie', 'Amenidades no nível; sem cabelo em nenhuma superfície'],
  'Guest-ready bathroom': ['Baño listo para el huésped', 'Banheiro pronto para o hóspede'],
  'Clean sink, vanity, and mirror': ['Limpiar lavabo, tocador y espejo', 'Limpar pia, bancada e espelho'],
  'Restock paper and hand soap; stage hand towel': ['Reponer papel y jabón de manos; acomodar toalla de mano', 'Repor papel e sabonete; arrumar toalha de rosto'],
  'Toilet flushes and refills; sink drains': ['El inodoro descarga y se llena; el lavabo drena', 'O vaso dá descarga e enche; a pia escoa'],
  'Guest-ready half bath': ['Medio baño listo para el huésped', 'Lavabo pronto para o hóspede'],
  'Wash, dry, and fold all used linens and towels': ['Lavar, secar y doblar toda la ropa de cama y toallas usadas', 'Lavar, secar e dobrar toda a roupa de cama e toalhas usadas'],
  'Empty lint trap; wipe washer and dryer': ['Vaciar el filtro de pelusa; limpiar lavadora y secadora', 'Esvaziar o filtro de fiapos; limpar lavadora e secadora'],
  'No laundry left in machines': ['No queda ropa en las máquinas', 'Nenhuma roupa deixada nas máquinas'],
  'Washer and dryer run': ['Lavadora y secadora funcionan', 'Lavadora e secadora funcionam'],
  'Laundry area reset': ['Área de lavado en orden', 'Área de serviço arrumada'],
  'Dust and wipe desk and surfaces': ['Sacudir y limpiar escritorio y superficies', 'Tirar o pó e limpar mesa e superfícies'],
  'Desk lamp and outlets work': ['Lámpara de escritorio y enchufes funcionan', 'Luminária de mesa e tomadas funcionam'],
  'Guest-ready office': ['Oficina lista para el huésped', 'Escritório pronto para o hóspede'],
  'Wipe surfaces and equipment': ['Limpiar superficies y equipo', 'Limpar superfícies e equipamentos'],
  'Reset games, controllers, and furniture': ['Acomodar juegos, controles y muebles', 'Arrumar jogos, controles e móveis'],
  'Consoles / equipment power on': ['Consolas / equipo encienden', 'Consoles / equipamentos ligam'],
  'Guest-ready game room': ['Sala de juegos lista para el huésped', 'Sala de jogos pronta para o hóspede'],
  'Reset furniture and bedding': ['Acomodar muebles y ropa de cama', 'Arrumar móveis e roupa de cama'],
  'Lights work; railing secure': ['Luces funcionan; barandal firme', 'Luzes funcionam; corrimão firme'],
  'Guest-ready loft': ['Altillo listo para el huésped', 'Mezanino pronto para o hóspede'],
  'Sweep deck or patio': ['Barrer terraza o patio', 'Varrer deck ou pátio'],
  'Wipe outdoor furniture and arrange': ['Limpiar y acomodar muebles de exterior', 'Limpar e arrumar móveis externos'],
  'Remove trash and cigarette butts': ['Recoger basura y colillas', 'Recolher lixo e bitucas de cigarro'],
  'Outdoor lights work; doors lock': ['Luces exteriores funcionan; puertas cierran con llave', 'Luzes externas funcionam; portas trancam'],
  'Guest-ready patio / deck': ['Patio / terraza listo para el huésped', 'Pátio / deck pronto para o hóspede'],
  'Skim surface and clear debris': ['Limpiar la superficie y retirar residuos', 'Limpar a superfície e retirar detritos'],
  'Arrange pool furniture and towels': ['Acomodar muebles de alberca y toallas', 'Arrumar móveis da piscina e toalhas'],
  'Gate and safety cover secured': ['Reja y cubierta de seguridad aseguradas', 'Portão e capa de segurança fechados'],
  'Water clear; pump running': ['Agua clara; bomba funcionando', 'Água limpa; bomba funcionando'],
  'Pool area reset': ['Área de alberca en orden', 'Área da piscina arrumada'],
  'Remove debris; wipe cover and rim': ['Retirar residuos; limpiar cubierta y borde', 'Retirar detritos; limpar capa e borda'],
  'Cover secured; temperature set per property': ['Cubierta asegurada; temperatura según la propiedad', 'Capa fechada; temperatura conforme a propriedade'],
  'Water clear; jets run': ['Agua clara; los chorros funcionan', 'Água limpa; jatos funcionam'],
  'Hot tub covered and reset': ['Jacuzzi cubierto y en orden', 'Hidromassagem coberta e arrumada'],
  'Scrape grates; wipe exterior': ['Raspar las parrillas; limpiar por fuera', 'Raspar as grelhas; limpar por fora'],
  'Propane connected and turned off; tank not empty': ['Gas conectado y cerrado; tanque no vacío', 'Gás conectado e fechado; botijão não vazio'],
  'Grill clean and covered': ['Asador limpio y cubierto', 'Churrasqueira limpa e coberta'],
  'Sweep floor; remove trash': ['Barrer el piso; sacar la basura', 'Varrer o piso; retirar o lixo'],
  'Door closes and locks': ['La puerta cierra y asegura', 'A porta fecha e tranca'],
  'Garage reset': ['Cochera en orden', 'Garagem arrumada'],
  'Sweep entry; shake out mats': ['Barrer la entrada; sacudir tapetes', 'Varrer a entrada; bater os tapetes'],
  'Wipe door, handle, and lockbox': ['Limpiar puerta, manija y caja de llaves', 'Limpar porta, maçaneta e cofre de chaves'],
  'Lock / keypad works; porch light on': ['Cerradura / teclado funciona; luz del porche encendida', 'Fechadura / teclado funciona; luz da varanda acesa'],
  'Entry as the guest sees it': ['La entrada como la ve el huésped', 'A entrada como o hóspede a vê'],
  'Walk the exterior; remove trash and debris': ['Recorrer el exterior; recoger basura y residuos', 'Percorrer a área externa; recolher lixo e detritos'],
  'Exterior lights and house number visible': ['Luces exteriores y número de la casa visibles', 'Luzes externas e número da casa visíveis'],
  'Bins out / returned per schedule': ['Botes de basura afuera / guardados según el calendario', 'Lixeiras para fora / recolhidas conforme o cronograma'],
  'Exterior / curb view': ['Vista exterior / desde la calle', 'Vista externa / da rua'],
  'All trash removed from the property': ['Toda la basura retirada de la propiedad', 'Todo o lixo retirado da propriedade'],
  'Laundry accounted for': ['Ropa de cama contabilizada', 'Roupa de cama conferida'],
  'Supplies and restock complete': ['Insumos y reposición completos', 'Suprimentos e reposição completos'],
  'Thermostat set to property standard': ['Termostato según el estándar de la propiedad', 'Termostato conforme o padrão da propriedade'],
  'Windows and doors checked and locked': ['Ventanas y puertas revisadas y cerradas con llave', 'Janelas e portas verificadas e trancadas'],
  'Lights set per property standard': ['Luces según el estándar de la propiedad', 'Luzes conforme o padrão da propriedade'],
  'No visible hair or debris anywhere': ['Sin cabello ni residuos visibles en ningún lado', 'Sem cabelo ou sujeira visível em lugar nenhum'],
  'No unresolved issue left unreported': ['Ningún problema pendiente sin reportar', 'Nenhum problema pendente sem relatar'],
  'Final readiness evidence': ['Evidencia final de que está listo', 'Evidência final de prontidão'],

  // ── Web checklist templates — Compact STR
  'Wipe counters, stovetop, microwave, fridge': ['Limpiar cubiertas, estufa, microondas, refrigerador', 'Limpar bancadas, fogão, micro-ondas, geladeira'],
  'Wash dishes, empty trash': ['Lavar trastes, sacar la basura', 'Lavar louça, tirar o lixo'],
  'Restock coffee, soap, basics': ['Reponer café, jabón, básicos', 'Repor café, sabonete, itens básicos'],
  'Dust all surfaces and electronics': ['Sacudir todas las superficies y electrónicos', 'Tirar o pó de todas as superfícies e eletrônicos'],
  'Vacuum couch, floor, and arrange pillows': ['Aspirar sofá y piso, acomodar cojines', 'Aspirar sofá e piso, arrumar almofadas'],
  'Dust nightstands and dresser': ['Sacudir burós y cómoda', 'Tirar o pó de criados-mudos e cômoda'],
  'Vacuum floor and check under bed': ['Aspirar el piso y revisar bajo la cama', 'Aspirar o piso e verificar embaixo da cama'],
  'Scrub toilet, shower, sink, mirror': ['Tallar inodoro, regadera, lavabo, espejo', 'Esfregar vaso, chuveiro, pia, espelho'],
  'Restock paper, soap, towels': ['Reponer papel, jabón, toallas', 'Repor papel, sabonete, toalhas'],
  'Check thermostat, lock doors, lights off': ['Revisar termostato, cerrar puertas, apagar luces', 'Verificar termostato, trancar portas, apagar luzes'],
  // Family STR
  'Second guest bedroom — strip and remake bed': ['Segundo dormitorio de huéspedes — quitar y tender la cama', 'Segundo quarto de hóspedes — desfazer e arrumar a cama'],
  'Second guest bedroom — dust and vacuum': ['Segundo dormitorio de huéspedes — sacudir y aspirar', 'Segundo quarto de hóspedes — tirar o pó e aspirar'],
  'Second guest bathroom — full clean': ['Segundo baño de huéspedes — limpieza completa', 'Segundo banheiro de hóspedes — limpeza completa'],
  'Check board games and toys are reset for next family': ['Revisar que juegos de mesa y juguetes estén en orden para la siguiente familia', 'Verificar se jogos de tabuleiro e brinquedos estão arrumados para a próxima família'],
  'Check pool/hot tub area is clean (if applicable)': ['Revisar que el área de alberca/jacuzzi esté limpia (si aplica)', 'Verificar se a área da piscina/hidromassagem está limpa (se houver)'],
  'Verify all bedrooms have fresh towels stacked': ['Verificar que todos los dormitorios tengan toallas limpias apiladas', 'Verificar se todos os quartos têm toalhas limpas empilhadas'],
  'Check baby gear (high chair, pack-n-play) is clean if present': ['Revisar que el equipo de bebé (silla alta, corral) esté limpio si lo hay', 'Verificar se os itens de bebê (cadeirão, berço portátil) estão limpos, se houver'],
  // Deep Clean
  'Clean oven interior with degreaser': ['Limpiar el interior del horno con desengrasante', 'Limpar o interior do forno com desengordurante'],
  'Pull out fridge, clean behind and underneath': ['Mover el refrigerador, limpiar atrás y debajo', 'Afastar a geladeira, limpar atrás e embaixo'],
  'Clean inside dishwasher (run cleaning cycle)': ['Limpiar el lavavajillas por dentro (ciclo de limpieza)', 'Limpar a lava-louças por dentro (ciclo de limpeza)'],
  'Wipe inside all cabinets and drawers': ['Limpiar por dentro todos los gabinetes y cajones', 'Limpar por dentro todos os armários e gavetas'],
  'Descale faucet and clean garbage disposal': ['Quitar el sarro de la llave y limpiar el triturador', 'Remover calcário da torneira e limpar o triturador'],
  'Wipe baseboards and door frames': ['Limpiar zoclos y marcos de puertas', 'Limpar rodapés e batentes de portas'],
  'Move furniture and vacuum beneath': ['Mover muebles y aspirar debajo', 'Afastar móveis e aspirar embaixo'],
  'Steam clean upholstered furniture': ['Limpiar con vapor los muebles tapizados', 'Limpar a vapor os móveis estofados'],
  'Dust ceiling fans, light fixtures, vents': ['Sacudir ventiladores de techo, lámparas, rejillas', 'Tirar o pó de ventiladores de teto, luminárias, saídas de ar'],
  'Wash windows inside and out (reachable)': ['Lavar ventanas por dentro y por fuera (las alcanzables)', 'Lavar janelas por dentro e por fora (as alcançáveis)'],
  'Flip and rotate mattress': ['Voltear y rotar el colchón', 'Virar e girar o colchão'],
  'Wash mattress protector and pillow covers': ['Lavar protector de colchón y fundas de almohada', 'Lavar protetor de colchão e capas de travesseiro'],
  'Wipe baseboards, door frames, vents': ['Limpiar zoclos, marcos de puertas, rejillas', 'Limpar rodapés, batentes, saídas de ar'],
  'Re-caulk shower if mildew is present': ['Resellar la regadera si hay moho', 'Refazer o rejunte/silicone do chuveiro se houver mofo'],
  'Deep-clean grout lines': ['Limpiar a fondo las juntas', 'Limpar a fundo os rejuntes'],
  'Clean exhaust fan vent': ['Limpiar la rejilla del extractor', 'Limpar a grade do exaustor'],
  'Wipe inside vanity drawers and under sink': ['Limpiar por dentro los cajones del tocador y bajo el lavabo', 'Limpar por dentro as gavetas do gabinete e embaixo da pia'],
  'Run washer cleaning cycle': ['Correr el ciclo de limpieza de la lavadora', 'Rodar o ciclo de limpeza da lavadora'],
  'Vacuum dryer vent line': ['Aspirar el ducto de la secadora', 'Aspirar o duto da secadora'],
  'Pressure wash patio/deck if needed': ['Lavar a presión patio/terraza si hace falta', 'Lavar com pressão o pátio/deck se necessário'],
  'Clean outdoor furniture thoroughly': ['Limpiar a fondo los muebles de exterior', 'Limpar a fundo os móveis externos'],
  // Move-Out
  'Clean oven interior thoroughly': ['Limpiar a fondo el interior del horno', 'Limpar a fundo o interior do forno'],
  'Empty and clean inside fridge and freezer': ['Vaciar y limpiar por dentro refrigerador y congelador', 'Esvaziar e limpar por dentro geladeira e freezer'],
  'Clean inside microwave and dishwasher': ['Limpiar por dentro microondas y lavavajillas', 'Limpar por dentro micro-ondas e lava-louças'],
  'Sanitize countertops and sink': ['Desinfectar cubiertas y tarja', 'Higienizar bancadas e pia'],
  'Mop floor and wipe baseboards': ['Trapear el piso y limpiar zoclos', 'Passar pano no piso e limpar rodapés'],
  'Patch and touch up wall nail holes if needed': ['Resanar y retocar agujeros de clavos si hace falta', 'Tapar e retocar furos de prego na parede se necessário'],
  'Vacuum / shampoo all carpets': ['Aspirar / lavar todas las alfombras', 'Aspirar / lavar todos os carpetes'],
  'Wipe baseboards, door frames, light switches': ['Limpiar zoclos, marcos de puertas, apagadores', 'Limpar rodapés, batentes, interruptores'],
  'Wash windows inside': ['Lavar ventanas por dentro', 'Lavar janelas por dentro'],
  'Empty closet completely, wipe shelves': ['Vaciar el clóset por completo, limpiar repisas', 'Esvaziar o armário por completo, limpar prateleiras'],
  'Vacuum / shampoo carpet': ['Aspirar / lavar la alfombra', 'Aspirar / lavar o carpete'],
  'Scrub tub/shower, descale fixtures': ['Tallar tina/regadera, quitar sarro de las llaves', 'Esfregar banheira/chuveiro, remover calcário dos metais'],
  'Clean toilet inside, base, behind': ['Limpiar el inodoro por dentro, la base y atrás', 'Limpar o vaso por dentro, na base e atrás'],
  'Empty and wipe inside all cabinets': ['Vaciar y limpiar por dentro todos los gabinetes', 'Esvaziar e limpar por dentro todos os armários'],
  'Polish mirror and chrome': ['Pulir espejo y cromados', 'Polir espelho e metais'],
  'Sweep patio, remove all personal items': ['Barrer el patio, retirar todos los objetos personales', 'Varrer o pátio, retirar todos os itens pessoais'],
  'Check garage — sweep and remove any items': ['Revisar la cochera — barrer y retirar objetos', 'Verificar a garagem — varrer e retirar itens'],
  'Replace HVAC filter': ['Cambiar el filtro del aire acondicionado', 'Trocar o filtro do ar-condicionado'],
  'Replace burnt-out lightbulbs': ['Cambiar focos fundidos', 'Trocar lâmpadas queimadas'],
  // Recurring Residential
  'Wipe countertops, stovetop, and backsplash': ['Limpiar cubiertas, estufa y salpicadero', 'Limpar bancadas, fogão e revestimento'],
  'Clean exterior of all appliances': ['Limpiar por fuera todos los electrodomésticos', 'Limpar por fora todos os eletrodomésticos'],
  'Wash visible dishes; run dishwasher if full': ['Lavar los trastes a la vista; correr el lavavajillas si está lleno', 'Lavar a louça à vista; rodar a lava-louças se estiver cheia'],
  'Wipe down sink and faucet': ['Limpiar tarja y llave', 'Limpar pia e torneira'],
  'Empty trash, replace liner': ['Sacar la basura, poner bolsa nueva', 'Tirar o lixo, trocar o saco'],
  'Vacuum couch and floor': ['Aspirar sofá y piso', 'Aspirar sofá e piso'],
  'Tidy magazines, throws, pillows': ['Ordenar revistas, mantas, cojines', 'Organizar revistas, mantas, almofadas'],
  'Make bed (do not change linens unless requested)': ['Tender la cama (no cambiar sábanas salvo que lo pidan)', 'Arrumar a cama (não trocar a roupa de cama, salvo se pedirem)'],
  'Dust surfaces, vacuum floor': ['Sacudir superficies, aspirar el piso', 'Tirar o pó das superfícies, aspirar o piso'],
  'Clean toilet, shower, sink, mirror': ['Limpiar inodoro, regadera, lavabo, espejo', 'Limpar vaso, chuveiro, pia, espelho'],
  'Replace hand towels': ['Cambiar toallas de mano', 'Trocar toalhas de rosto'],
  'Clean toilet, sink, mirror, mop floor': ['Limpiar inodoro, lavabo, espejo, trapear el piso', 'Limpar vaso, pia, espelho, passar pano no piso'],
  'Empty all wastebaskets': ['Vaciar todos los botes de basura', 'Esvaziar todas as lixeiras'],
  // PM Walkthrough
  'Verify all appliances powered and functional': ['Verificar que todos los electrodomésticos enciendan y funcionen', 'Verificar se todos os eletrodomésticos ligam e funcionam'],
  'Check sink for leaks or slow drainage': ['Revisar fugas o drenaje lento en la tarja', 'Verificar vazamentos ou escoamento lento na pia'],
  'Photograph any visible damage or wear': ['Fotografiar cualquier daño o desgaste visible', 'Fotografar qualquer dano ou desgaste visível'],
  'Test TV, AC remote, ceiling fan': ['Probar TV, control del aire, ventilador de techo', 'Testar TV, controle do ar, ventilador de teto'],
  'Check for stains on couch and rugs': ['Revisar manchas en sofá y tapetes', 'Verificar manchas no sofá e tapetes'],
  'Verify bed and bedding condition': ['Verificar el estado de la cama y la ropa de cama', 'Verificar o estado da cama e da roupa de cama'],
  'Photograph any damage to walls or furniture': ['Fotografiar daños en paredes o muebles', 'Fotografar danos em paredes ou móveis'],
  'Test all faucets, shower, and toilet flush': ['Probar todas las llaves, la regadera y la descarga', 'Testar todas as torneiras, o chuveiro e a descarga'],
  'Check for caulk damage or mildew': ['Revisar sellador dañado o moho', 'Verificar silicone danificado ou mofo'],
  'Verify exterior locks and lighting work': ['Verificar que cerraduras y luces exteriores funcionen', 'Verificar se fechaduras e luzes externas funcionam'],
  'Note any landscaping concerns': ['Anotar cualquier problema de jardinería', 'Anotar qualquer problema de jardinagem'],
  'Test smoke detectors, check batteries': ['Probar detectores de humo, revisar baterías', 'Testar detectores de fumaça, verificar pilhas'],
  'Verify thermostat is operational': ['Verificar que el termostato funcione', 'Verificar se o termostato funciona'],
  'Note HVAC filter condition': ['Anotar el estado del filtro del aire', 'Anotar o estado do filtro do ar'],
  // Pet-Friendly
  'Lint roll all upholstered furniture for pet hair': ['Pasar rodillo quitapelusa a los muebles tapizados por pelo de mascota', 'Passar rolo adesivo nos estofados para tirar pelo de animal'],
  'Extra vacuum pass with pet-hair attachment': ['Pasada extra de aspiradora con accesorio para pelo de mascota', 'Passada extra de aspirador com bocal para pelo de animal'],
  'Lint roll bedding for pet hair before stripping': ['Pasar rodillo quitapelusa a la ropa de cama antes de quitarla', 'Passar rolo adesivo na roupa de cama antes de retirá-la'],
  'Vacuum under bed thoroughly for fur dust bunnies': ['Aspirar bien bajo la cama por bolas de pelo', 'Aspirar bem embaixo da cama por bolas de pelo'],
  'Vacuum under bed and along baseboards': ['Aspirar bajo la cama y a lo largo de los zoclos', 'Aspirar embaixo da cama e ao longo dos rodapés'],
  'Pick up pet waste in yard / patio area': ['Recoger desechos de mascota en el jardín / patio', 'Recolher dejetos de animal no quintal / pátio'],
  'Hose down patio if pet was outside': ['Lavar el patio con manguera si la mascota estuvo afuera', 'Lavar o pátio com mangueira se o animal ficou fora'],
  'Use pet-safe deodorizer on carpets': ['Usar desodorizante seguro para mascotas en alfombras', 'Usar desodorizador seguro para animais nos carpetes'],
  'Empty and clean any pet bowls left out': ['Vaciar y limpiar los platos de mascota que hayan quedado', 'Esvaziar e limpar as tigelas de animal deixadas'],
  // Final (web) verify lines
  'All interior lights off except designated night lights': ['Todas las luces interiores apagadas salvo las luces nocturnas designadas', 'Todas as luzes internas apagadas, exceto as luzes noturnas designadas'],
  'Every door accessed is locked, including interior suites': ['Toda puerta usada queda cerrada con llave, incluidas las suites interiores', 'Toda porta usada fica trancada, incluindo as suítes internas'],
  'Alarm armed and panel confirms set': ['Alarma activada y el panel lo confirma', 'Alarme ativado e o painel confirma'],
  'Keys and fobs returned to the agreed location': ['Llaves y controles devueltos al lugar acordado', 'Chaves e controles devolvidos ao local combinado'],
  'Nothing propped, wedged, or left disabled': ['Nada apuntalado, atorado ni desactivado', 'Nada escorado, calçado ou deixado desativado'],
  // Office — nightly
  'Glass doors and side lights spot-cleaned, both sides': ['Puertas de vidrio y paneles laterales limpiados por ambos lados', 'Portas de vidro e painéis laterais limpos dos dois lados'],
  'Entry mats vacuumed or shaken out': ['Tapetes de entrada aspirados o sacudidos', 'Tapetes de entrada aspirados ou batidos'],
  'Reception desk and counter wiped, papers left undisturbed': ['Escritorio y mostrador de recepción limpios, sin mover papeles', 'Mesa e balcão da recepção limpos, sem mexer nos papéis'],
  'Seating and side tables wiped, cushions straightened': ['Asientos y mesas laterales limpios, cojines acomodados', 'Assentos e mesas laterais limpos, almofadas ajeitadas'],
  'Trash emptied, liner replaced': ['Basura vaciada, bolsa nueva', 'Lixo esvaziado, saco trocado'],
  'Floor vacuumed or mopped to the edges': ['Piso aspirado o trapeado hasta las orillas', 'Piso aspirado ou com pano até as bordas'],
  'All desk-side trash and recycling emptied': ['Basura y reciclaje de todos los escritorios vaciados', 'Lixo e reciclagem de todas as mesas esvaziados'],
  'Clear desk surfaces wiped — around personal items, not through them': ['Superficies despejadas limpias — alrededor de objetos personales, sin moverlos', 'Superfícies livres limpas — ao redor dos itens pessoais, sem mexer neles'],
  'Monitors and keyboards dusted dry, no spray on screens': ['Monitores y teclados sacudidos en seco, sin rociar las pantallas', 'Monitores e teclados sem pó, a seco, sem spray nas telas'],
  'Traffic lanes vacuumed, chairs returned to desks': ['Pasillos aspirados, sillas devueltas a los escritorios', 'Corredores aspirados, cadeiras devolvidas às mesas'],
  'Clear surfaces dusted, desk left as found': ['Superficies despejadas sacudidas, escritorio como se encontró', 'Superfícies livres sem pó, mesa deixada como estava'],
  'Floor vacuumed': ['Piso aspirado', 'Piso aspirado'],
  'Table wiped and polished, chairs squared to the table': ['Mesa limpia y pulida, sillas alineadas', 'Mesa limpa e polida, cadeiras alinhadas'],
  'Whiteboard cleaned unless marked DO NOT ERASE': ['Pizarrón limpio salvo que diga NO BORRAR', 'Quadro branco limpo, salvo se marcado NÃO APAGAR'],
  'Trash emptied, floor vacuumed': ['Basura vaciada, piso aspirado', 'Lixo esvaziado, piso aspirado'],
  'Toilets and urinals cleaned inside, outside and at the base': ['Inodoros y mingitorios limpios por dentro, por fuera y en la base', 'Vasos e mictórios limpos por dentro, por fora e na base'],
  'Sinks, faucets, counters and mirrors polished': ['Lavabos, llaves, cubiertas y espejos pulidos', 'Pias, torneiras, bancadas e espelhos polidos'],
  'Partitions and door handles disinfected': ['Divisiones y manijas desinfectadas', 'Divisórias e maçanetas desinfetadas'],
  'Restock toilet paper, seat covers, hand soap, paper towels': ['Reponer papel higiénico, cubreasientos, jabón de manos, toallas de papel', 'Repor papel higiênico, protetores de assento, sabonete, papel-toalha'],
  'Floor swept and mopped, corners and behind the door included': ['Piso barrido y trapeado, incluidas esquinas y detrás de la puerta', 'Piso varrido e com pano, incluindo cantos e atrás da porta'],
  'Restroom left fully stocked and dry': ['Sanitario surtido y seco', 'Banheiro abastecido e seco'],
  'Counters, table tops and chair backs wiped': ['Cubiertas, mesas y respaldos limpios', 'Bancadas, mesas e encostos limpos'],
  'Sink emptied and scrubbed, no dishes left standing': ['Tarja vacía y tallada, sin trastes', 'Pia vazia e esfregada, sem louça'],
  'Microwave cleaned inside and out': ['Microondas limpio por dentro y por fuera', 'Micro-ondas limpo por dentro e por fora'],
  'Appliance fronts wiped — fridge, dishwasher, coffee machine': ['Frentes de electrodomésticos limpios — refrigerador, lavavajillas, cafetera', 'Frentes dos eletrodomésticos limpos — geladeira, lava-louças, cafeteira'],
  'Trash and recycling emptied, liners replaced': ['Basura y reciclaje vaciados, bolsas nuevas', 'Lixo e reciclagem esvaziados, sacos trocados'],
  'Floor swept and mopped': ['Piso barrido y trapeado', 'Piso varrido e com pano'],
  'Drinking fountains cleaned and polished': ['Bebederos limpios y pulidos', 'Bebedouros limpos e polidos'],
  'Door handles and push plates disinfected': ['Manijas y placas de empuje desinfectadas', 'Maçanetas e placas de empurrar desinfetadas'],
  'Floors vacuumed or dust-mopped end to end': ['Pisos aspirados o mopeados de punta a punta', 'Pisos aspirados ou com mop seco de ponta a ponta'],
  'Mop heads rinsed and hung, sink cleaned': ['Trapeadores enjuagados y colgados, tarja limpia', 'Esfregões enxaguados e pendurados, tanque limpo'],
  'Cart restocked and closet left locked': ['Carrito surtido y cuarto cerrado con llave', 'Carrinho abastecido e depósito trancado'],
  // Office — monthly
  'Full glass detail including frames and thresholds': ['Detalle completo de vidrios, marcos y umbrales', 'Limpeza detalhada dos vidros, incluindo molduras e soleiras'],
  'High dust — ledges, frames, signage, light fixtures': ['Sacudir en alto — repisas, marcos, letreros, lámparas', 'Tirar o pó no alto — beirais, molduras, placas, luminárias'],
  'Upholstery vacuumed including under the cushions': ['Tapicería aspirada, incluido bajo los cojines', 'Estofados aspirados, incluindo embaixo das almofadas'],
  'High dust above sight line — partitions, shelf tops, cable trays': ['Sacudir por encima de la vista — divisiones, tope de repisas, canaletas', 'Tirar o pó acima da linha de visão — divisórias, topo de prateleiras, calhas de cabos'],
  'Edge vacuum along baseboards and under desks': ['Aspirar orillas a lo largo de zoclos y bajo escritorios', 'Aspirar bordas ao longo dos rodapés e embaixo das mesas'],
  'Chair bases and casters wiped': ['Bases y ruedas de sillas limpias', 'Bases e rodízios das cadeiras limpos'],
  'Baseboards wiped, corners edge-vacuumed': ['Zoclos limpios, esquinas aspiradas', 'Rodapés limpos, cantos aspirados'],
  'Chair upholstery vacuumed, table base and legs wiped': ['Tapicería de sillas aspirada, base y patas de mesa limpias', 'Estofado das cadeiras aspirado, base e pés da mesa limpos'],
  'Wall-mounted screen and mount dusted': ['Pantalla de pared y soporte sacudidos', 'Tela de parede e suporte sem pó'],
  'Tile and grout scrubbed, not just mopped': ['Azulejo y juntas tallados, no solo trapeados', 'Azulejo e rejunte esfregados, não só com pano'],
  'Vents and exhaust covers dusted': ['Rejillas y cubiertas de extractor sacudidas', 'Saídas de ar e tampas de exaustor sem pó'],
  'Partition tops and door frames wiped': ['Tope de divisiones y marcos de puertas limpios', 'Topo das divisórias e batentes limpos'],
  'Fridge interior cleaned, expired items removed': ['Interior del refrigerador limpio, artículos caducados retirados', 'Interior da geladeira limpo, itens vencidos retirados'],
  'Cabinet fronts and handles degreased': ['Frentes y manijas de gabinetes desengrasados', 'Frentes e puxadores dos armários desengordurados'],
  'Baseboards and door frames wiped full length': ['Zoclos y marcos de puertas limpios en todo su largo', 'Rodapés e batentes limpos em toda a extensão'],
  'Vents and returns dusted': ['Rejillas y retornos sacudidos', 'Saídas e retornos de ar sem pó'],
  // Medical / dental
  'Glass doors and mats cleaned': ['Puertas de vidrio y tapetes limpios', 'Portas de vidro e tapetes limpos'],
  'Every seat, arm rest and side table disinfected': ['Cada asiento, descansabrazos y mesa lateral desinfectados', 'Cada assento, braço e mesa lateral desinfetados'],
  'Reception glass and check-in counter cleaned': ['Vidrio de recepción y mostrador de registro limpios', 'Vidro da recepção e balcão de check-in limpos'],
  'Toys, magazines and shared items wiped or removed per practice policy': ['Juguetes, revistas y artículos compartidos limpiados o retirados según la política del consultorio', 'Brinquedos, revistas e itens compartilhados limpos ou retirados conforme a política da clínica'],
  'Trash emptied, floor vacuumed or mopped': ['Basura vaciada, piso aspirado o trapeado', 'Lixo esvaziado, piso aspirado ou com pano'],
  'Confirm the room is released for cleaning before entering': ['Confirmar que la sala esté liberada para limpieza antes de entrar', 'Confirmar que a sala foi liberada para limpeza antes de entrar'],
  'Exam table, stool and counter disinfected, full contact time observed': ['Mesa de exploración, banco y cubierta desinfectados, respetando el tiempo de contacto', 'Mesa de exame, banqueta e bancada desinfetados, respeitando o tempo de contato'],
  'Sink, faucet and dispensers cleaned and restocked': ['Lavabo, llave y dispensadores limpios y surtidos', 'Pia, torneira e dispensers limpos e abastecidos'],
  'Regular waste emptied — red bag and sharps containers NOT handled': ['Basura común vaciada — NO tocar bolsas rojas ni contenedores de punzocortantes', 'Lixo comum esvaziado — NÃO manusear sacos vermelhos nem coletores de perfurocortantes'],
  'Floor mopped with the practice-approved disinfectant': ['Piso trapeado con el desinfectante aprobado por el consultorio', 'Piso limpo com o desinfetante aprovado pela clínica'],
  'Chair, light handles and tray surfaces disinfected': ['Sillón, manijas de lámpara y bandejas desinfectados', 'Cadeira, alças do refletor e bandejas desinfetadas'],
  'Cabinet fronts and handles wiped': ['Frentes y manijas de gabinetes limpios', 'Frentes e puxadores dos armários limpos'],
  'Floor mopped, chair base included': ['Piso trapeado, incluida la base del sillón', 'Piso limpo, incluindo a base da cadeira'],
  'Confirm access is permitted before entering': ['Confirmar que el acceso esté permitido antes de entrar', 'Confirmar que o acesso é permitido antes de entrar'],
  'Counters cleaned around equipment — equipment itself not moved or wiped': ['Cubiertas limpias alrededor del equipo — sin mover ni limpiar el equipo', 'Bancadas limpas ao redor dos equipamentos — sem mover nem limpar os equipamentos'],
  'Floor mopped': ['Piso trapeado', 'Piso limpo com pano'],
  'Toilets cleaned inside, outside and at the base': ['Inodoros limpios por dentro, por fuera y en la base', 'Vasos limpos por dentro, por fora e na base'],
  'Sinks, counters, mirrors and dispensers cleaned and restocked': ['Lavabos, cubiertas, espejos y dispensadores limpios y surtidos', 'Pias, bancadas, espelhos e dispensers limpos e abastecidos'],
  'Handles, plates and grab rails disinfected': ['Manijas, placas y barras de apoyo desinfectadas', 'Maçanetas, placas e barras de apoio desinfetadas'],
  'Floor mopped, trash emptied': ['Piso trapeado, basura vaciada', 'Piso limpo, lixo esvaziado'],
  'Handrails, door handles and push plates disinfected': ['Pasamanos, manijas y placas de empuje desinfectados', 'Corrimãos, maçanetas e placas de empurrar desinfetados'],
  'Floors vacuumed or mopped': ['Pisos aspirados o trapeados', 'Pisos aspirados ou com pano'],
  'Counters, sink and table wiped; trash emptied; floor mopped': ['Cubiertas, tarja y mesa limpias; basura vaciada; piso trapeado', 'Bancadas, pia e mesa limpas; lixo esvaziado; piso limpo'],
  'Upholstery vacuumed and spot-treated': ['Tapicería aspirada y con manchas tratadas', 'Estofados aspirados e com manchas tratadas'],
  'High dust — frames, signage, vents, light fixtures': ['Sacudir en alto — marcos, letreros, rejillas, lámparas', 'Tirar o pó no alto — molduras, placas, saídas de ar, luminárias'],
  'Walls spot-washed at hand height and around the sink': ['Paredes lavadas por puntos a la altura de la mano y alrededor del lavabo', 'Paredes lavadas por pontos na altura da mão e ao redor da pia'],
  'Exam table base and stool casters detailed': ['Base de la mesa de exploración y ruedas del banco detalladas', 'Base da mesa de exame e rodízios da banqueta detalhados'],
  'Chair base, foot control and cable runs detailed': ['Base del sillón, pedal y cableado detallados', 'Base da cadeira, pedal e cabos detalhados'],
  'Cabinet interiors wiped where the practice permits': ['Interior de gabinetes limpio donde el consultorio lo permita', 'Interior dos armários limpo onde a clínica permitir'],
  'Floor edges and equipment surrounds detailed': ['Orillas del piso y alrededores del equipo detallados', 'Bordas do piso e entorno dos equipamentos detalhados'],
  'Tile and grout scrubbed; vents dusted': ['Azulejo y juntas tallados; rejillas sacudidas', 'Azulejo e rejunte esfregados; saídas de ar sem pó'],
  'Baseboards, door frames and vents wiped full length': ['Zoclos, marcos de puertas y rejillas limpios en todo su largo', 'Rodapés, batentes e saídas de ar limpos em toda a extensão'],

  // ── Default photo requirements (seed_default_photo_requirements_for_address)
  'Thermostat': ['Termostato', 'Termostato'],
  'Main door closed': ['Puerta principal cerrada', 'Porta principal fechada'],
  'Fireplace (if applicable)': ['Chimenea (si aplica)', 'Lareira (se houver)'],
  'Under sofa cushions': ['Bajo los cojines del sofá', 'Embaixo das almofadas do sofá'],
  'Wide room overview': ['Vista general de la habitación', 'Visão geral do cômodo'],
  'Remote controls — organized & clean': ['Controles remotos — ordenados y limpios', 'Controles remotos — organizados e limpos'],
  'Fridge — open': ['Refrigerador — abierto', 'Geladeira — aberta'],
  'Amenities (dish soap, paper towels, sponge)': ['Amenidades (jabón para trastes, toallas de papel, esponja)', 'Amenidades (detergente, papel-toalha, esponja)'],
  'Oven & stove': ['Horno y estufa', 'Forno e fogão'],
  'Cabinets — open': ['Gabinetes — abiertos', 'Armários — abertos'],
  'Cabinets — closed': ['Gabinetes — cerrados', 'Armários — fechados'],
  'Bedroom overview': ['Vista general del dormitorio', 'Visão geral do quarto'],
  'Under the bed — no trash': ['Bajo la cama — sin basura', 'Embaixo da cama — sem lixo'],
  'Bathroom overview': ['Vista general del baño', 'Visão geral do banheiro'],
  'Amenities stocked (towels, makeup wipes, toilet paper)': ['Amenidades surtidas (toallas, toallitas desmaquillantes, papel higiénico)', 'Amenidades abastecidas (toalhas, lenços de maquiagem, papel higiênico)'],
  'Toilet — close angle': ['Inodoro — toma cercana', 'Vaso — close'],
  'Bathtub — clean': ['Tina — limpia', 'Banheira — limpa'],
  'Special amenities (pool table, arcade, sauna)': ['Amenidades especiales (mesa de billar, arcade, sauna)', 'Amenidades especiais (mesa de sinuca, fliperama, sauna)'],
  'Room overview': ['Vista general', 'Visão geral do cômodo'],
  'Outdoor furniture — cleaned & staged': ['Muebles de exterior — limpios y acomodados', 'Móveis externos — limpos e arrumados'],
  'BBQ — open & clean (grease trap on)': ['Asador — abierto y limpio (con charola de grasa)', 'Churrasqueira — aberta e limpa (com coletor de gordura)'],
  'Back door access closed': ['Acceso de la puerta trasera cerrado', 'Acesso da porta dos fundos fechado'],
}

const IDX: Record<string, [string, string]> = {}
for (const k of Object.keys(V)) IDX[norm(k)] = V[k]

function norm(s: string): string {
  return s.trim().replace(/\s+/g, ' ').toLowerCase()
}

/** Seeded English data string → crew language for display. Unknown text passes through untouched. */
export function tv(lang: Language, text: string | null | undefined): string {
  if (!text) return text ?? ''
  if (lang === 'en') return text
  const i = lang === 'es' ? 0 : 1
  const key = norm(text)
  const hit = IDX[key]
  if (hit) return hit[i]
  // "Bedroom 2", "Living Room 2", "Bathroom 3" — carry the instance number.
  const m = key.match(/^(.*\S)\s+(\d+)$/)
  if (m) {
    const base = IDX[m[1]]
    if (base) return `${base[i]} ${m[2]}`
  }
  return text
}
